# Importing the libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [4]:
path = "Data_classification copy.csv"
df = pd.read_csv(path)
df.head

<bound method NDFrame.head of      Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1            

In [5]:
x = df.iloc[:, 0:10].values
y = df.iloc[:, 10].values
print(x)
print(y)

[[1000025       5       1 ...       3       1       1]
 [1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]
[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2

# Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [7]:
print(X_train)

[[1123061       6      10 ...       7       8      10]
 [1269574       4       1 ...       1       1       1]
 [1238948       8       5 ...       6       6       1]
 ...
 [1174841       5       3 ...       1       1       1]
 [1177027       3       1 ...       3       1       1]
 [ 428903       7       2 ...       3       3       1]]


In [8]:
print(X_test)

[[ 529329      10      10 ...       4      10      10]
 [ 320675       3       3 ...       7       1       1]
 [1246562      10       2 ...       1       1       2]
 ...
 [ 142932       7       6 ...       9      10       2]
 [1216694      10       8 ...       8       1       1]
 [ 730881       7       6 ...       7       4       6]]


In [9]:
print(Y_train)

[4 2 4 4 2 2 2 4 4 2 4 2 2 2 4 2 2 2 4 4 2 2 2 2 2 4 2 4 4 2 4 4 2 2 4 4 2
 2 4 2 2 2 2 4 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 4 2 4 4 4 2 4 2 4 4 2 4 4 2
 2 2 4 2 2 2 4 2 4 2 2 4 4 2 2 2 2 2 4 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2
 4 2 4 2 4 4 2 2 4 2 2 2 2 4 2 4 4 2 2 4 2 4 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2
 2 2 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 4 2 4 2 4 4 4 2 4 2 2 4 4 4 2 2 2 2 4 4
 4 4 2 2 2 2 4 2 4 2 4 4 4 2 2 4 2 2 2 2 4 4 2 4 4 2 4 2 2 2 2 4 4 4 2 2 2
 2 2 2 4 4 2 2 4 2 2 4 2 2 2 2 2 2 4 2 4 2 2 2 2 4 4 2 4 2 2 4 2 2 2 2 2 4
 2 2 4 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 4 2 4 2 4 4 2 2 4 4 2 2 2 4 2 2
 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 2 2 2 2 2 4 4 4 4 4 2 2 4 4 2 2 4 4 2 4
 2 2 4 4 2 2 2 2 4 4 2 4 2 2 2 2 2 2 2 4 2 2 2 2 4 4 4 2 2 2 4 2 2 2 2 2 4
 2 4 2 2 2 2 4 2 4 4 4 2 4 2 2 2 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 4 2 2 2 2 4
 4 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 2 2 2 4 2 2 2 2 2 2
 4 4 2 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2 4 2 2 2 4 4 4 2 4 2 2 2 2 4 4 2 2 2
 4 4 2 4 2 2 4 4 4 2 2 2 

In [10]:
print(Y_test)

[4 4 4 4 4 4 2 2 4 4 4 2 2 4 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 4 2 4 4
 4 2 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 4 2 2 2 2 2 2 4 4 4 4 2 4 2 2 2 2 2 4 4 4]


# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[ 0.0671248   0.56927669  2.21293723 ...  1.46831705  1.67397403
   5.04619452]
 [ 0.31104461 -0.15022579 -0.70400847 ... -0.99719123 -0.61754773
  -0.35032341]
 [ 0.26005741  1.28877918  0.59241185 ...  1.057399    1.01925353
  -0.35032341]
 ...
 [ 0.1533299   0.20952545 -0.05579831 ... -0.99719123 -0.61754773
  -0.35032341]
 [ 0.15696923 -0.50997704 -0.70400847 ... -0.17535514 -0.61754773
  -0.35032341]
 [-1.088533    0.92902794 -0.37990339 ... -0.17535514  0.03717278
  -0.35032341]]


In [13]:
print(X_test)

[[-0.92134038  2.00828167  2.21293723 ...  0.23556291  2.32869453
   5.04619452]
 [-1.26871464 -0.50997704 -0.05579831 ...  1.46831705 -0.61754773
  -0.35032341]
 [ 0.27273346  2.00828167 -0.37990339 ... -0.99719123 -0.61754773
   0.2492897 ]
 ...
 [-1.56462722  0.92902794  0.91651692 ...  2.29015314  2.32869453
   0.2492897 ]
 [ 0.2230082   2.00828167  1.56472708 ...  1.8792351  -0.61754773
  -0.35032341]
 [-0.58578977  0.92902794  0.91651692 ...  1.46831705  0.36453303
   2.64774211]]


# Decision Tree Classification Model

## Training model on the Training data set

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier_DTC = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_DTC.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Predicting the Test set results

In [15]:
Y_pred_DTC = classifier_DTC.predict(X_test)
print(Y_pred_DTC)

[4 4 2 4 4 4 2 2 4 4 4 4 2 2 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 4 2 4 4
 4 2 2 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 2 2 2 2 4 2 4 2 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 4 2 2 2 2 4 2 4 4 4 4 2 4 2 2 2 2 2 4 4 4]


## Making the Confusion Matrix and Accuracy

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_DTC)
accuracy = accuracy_score(Y_test, Y_pred_DTC)
print(f"Confusion Matrix:\n{cm} \nAccuracy : {accuracy}")

Confusion Matrix:
[[84  5]
 [ 2 46]] 
Accuracy : 0.948905109489051


# K-Nearest Neighbors Classification Model

## Training model on the Training data set

In [17]:
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN = KNeighborsClassifier( n_neighbors = 5, algorithm = 'kd_tree', leaf_size = 25,  metric = 'minkowski', p = 2)
classifier_KNN.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=25)

## Predicting the Test set results

In [18]:
Y_pred_KNN = classifier_KNN.predict(X_test)
print(Y_pred_KNN)

[4 4 2 4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 2 2 4 4
 4 2 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 4 2 2 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 4 4 4]


## Making the Confusion Matrix and Accuracy

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_KNN)
accuracy = accuracy_score(Y_test, Y_pred_KNN)
print(f"Confusion Matrix:\n{cm} \nAccuracy : {accuracy}")

Confusion Matrix:
[[88  1]
 [ 4 44]] 
Accuracy : 0.9635036496350365


# Kernel SVM Classification Model

## Training model on the Training data set

In [20]:
from sklearn.svm import SVC
classifier_SVC = SVC(kernel='poly', random_state=0)
classifier_SVC.fit(X_train, Y_train)

SVC(kernel='poly', random_state=0)

## Predicting the Test set results

In [21]:
Y_pred_SVC = classifier_SVC.predict(X_test)
print(Y_pred_SVC)

[4 4 2 4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 2 2 4 4
 2 2 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 4 4 2 2 2 2 2 2 4
 2 2 4 2 2 4 2 2 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 4 4 4]


## Making the Confusion Matrix and Accuracy

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_SVC)
accuracy = accuracy_score(Y_test, Y_pred_SVC)
print(f"Confusion Matrix:\n{cm} \nAccuracy : {accuracy}")

Confusion Matrix:
[[88  1]
 [ 7 41]] 
Accuracy : 0.9416058394160584


# Random Forest Classification Model

## Training model on the Training data set

In [23]:
from sklearn.ensemble import RandomForestClassifier
classifier_RFC = RandomForestClassifier(n_estimators = 10 ,criterion = 'entropy', random_state = 0)
classifier_RFC.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test set results

In [24]:
Y_pred_RFC = classifier_RFC.predict(X_test)
print(Y_pred_RFC)

[4 4 2 4 4 4 2 2 4 4 4 2 2 4 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 2 2 4 4
 4 2 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 2 2 2 2 4 2 4 2 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 4 2 2 2 2 4 2 4 4 4 4 2 4 2 2 2 2 2 4 4 4]


## Making the Confusion Matrix and Accuracy

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_RFC)
accuracy = accuracy_score(Y_test, Y_pred_RFC)
print(f"Confusion Matrix:\n{cm} \nAccuracy : {accuracy}")

Confusion Matrix:
[[87  2]
 [ 2 46]] 
Accuracy : 0.9708029197080292


# Naive Bayes Classification Model

## Training model on the Training data set

In [26]:
from sklearn.naive_bayes import GaussianNB
classifier_NBC = GaussianNB()
classifier_NBC.fit(X_train, Y_train)

GaussianNB()

## Predicting the Test set results

In [27]:
Y_pred_NBC = classifier_NBC.predict(X_test)
print(Y_pred_NBC)

[4 4 4 4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 2 4 2 2 2 2 4 2 2 2 2 2 2 4 4 4 2 4 4
 4 2 2 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 4 4 2 4 2 4 2 4 2 2 2 2 2 2 2 2 4 2
 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 2 2 2 2 2 2 4 2 4 4 2 2 2 2 4 2 4
 2 2 4 2 4 4 2 2 2 2 4 2 4 4 4 4 2 4 2 2 2 2 2 4 4 4]


## Making the Confusion Matrix and Accuracy

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_NBC)
accuracy = accuracy_score(Y_test, Y_pred_NBC)
print(f"Confusion Matrix:\n{cm} \nAccuracy : {accuracy}")

Confusion Matrix:
[[86  3]
 [ 1 47]] 
Accuracy : 0.9708029197080292
