# Importing the libraries

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the Dataset

In [32]:
path = "Data_regression.csv"
df = pd.read_csv(path)
df.head

<bound method NDFrame.head of          AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]>

In [33]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


# Splitting Dataset into Traning set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [35]:
X_train

array([[  24.23,   49.3 , 1003.61,   74.44],
       [  20.94,   44.58, 1016.98,   59.65],
       [   9.68,   39.96, 1026.09,   99.28],
       ...,
       [  12.33,   39.85, 1012.53,   66.04],
       [  12.02,   39.69, 1006.05,   84.66],
       [  10.25,   37.14, 1013.14,   70.73]])

In [36]:
X_test

array([[  19.6 ,   48.14, 1013.18,   68.71],
       [  21.28,   70.32, 1011.55,   88.05],
       [  28.62,   59.14, 1016.36,   53.1 ],
       ...,
       [  28.33,   68.14, 1004.63,   71.21],
       [  23.29,   68.51, 1013.19,   77.81],
       [  17.37,   41.23,  998.79,   68.44]])

In [37]:
Y_train

array([440.65, 463.69, 470.22, ..., 479.32, 470.17, 474.37])

In [38]:
Y_test

array([456.57, 438.7 , 436.09, ..., 431.27, 441.17, 461.08])

# 1. **Simple Linear Regression Model**

## Training the model on the Training data set

In [39]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train,Y_train)

LinearRegression()

## Prediciting the Test Set Results

In [40]:
Y_Predict_LR = clf.predict(X_test)
print(Y_Predict_LR)

[456.61687904 445.01924142 438.86942695 ... 433.81610549 443.16667161
 461.80248105]


## Calculate R-squared (R^2) Value

In [41]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, Y_Predict_LR)

print("R-squared (R^2) value for Linear Regression:", r2)

R-squared (R^2) value for Linear Regression: 0.9351857555372783


# 2. **Polynomial Linear Regression Model**

## Training the model on the Training data set

In [42]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures( degree = 10)
x_poly = poly_reg.fit_transform(X_train)
linear_reg_2 = LinearRegression()
linear_reg_2.fit(x_poly, Y_train)

LinearRegression()

## Prediciting the Test Set Results

In [43]:
poly_reg = PolynomialFeatures( degree = 10)
x_poly_test = poly_reg.fit_transform(X_test)
Y_Predict_PLR = linear_reg_2.predict(x_poly_test)
print(Y_Predict_PLR)

[454.34218336 442.69427454 441.8019878  ... 432.87626307 440.72299825
 459.21091047]


## Calculate R-squared (R^2) Value

In [44]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, Y_Predict_PLR)

print("R-squared (R^2) value for Polynomial Linear Regression:", r2)

R-squared (R^2) value for Polynomial Linear Regression: 0.948410276008181


# 3. **Decision Tree Regression Model**

## Training the model on the Training data set

In [45]:
from sklearn.tree import DecisionTreeRegressor

regressor_DTR = DecisionTreeRegressor()
regressor_DTR.fit(X_train, Y_train)

DecisionTreeRegressor()

## Prediciting the Test Set Results

In [46]:
y_pred_DTR = regressor_DTR.predict(X_test)
print(y_pred_DTR)

[451.77 440.   439.28 ... 430.21 441.61 459.1 ]


## Calculate R-squared (R^2) Value

In [47]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, y_pred_DTR)

print("R-squared (R^2) value for Decision Tree Regressor:", r2)

R-squared (R^2) value for Decision Tree Regressor: 0.9355151742080214


# 4. **Random Forest Regression Model**

## Training the model on the Training data set

In [48]:
from sklearn.ensemble import RandomForestRegressor

regressor_RFR = RandomForestRegressor()
regressor_RFR.fit(X_train, Y_train)

RandomForestRegressor()

## Prediciting the Test Set Results

In [49]:
y_pred_RFR = regressor_RFR.predict(X_test)
print(y_pred_RFR)

[454.3955 440.0869 439.5111 ... 432.3731 439.6888 460.424 ]


## Calculate R-squared (R^2) Value

In [50]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, y_pred_RFR)

print("R-squared (R^2) value for Random Forest Regression:", r2)

R-squared (R^2) value for Random Forest Regression: 0.9671288991363769


# 5. **Support Vector Regression Model**

## Training the model on the Training data set

In [51]:
from sklearn.svm import SVR
regressor_SVR = SVR(kernel='rbf')
regressor_SVR.fit(X_train,Y_train)

SVR()

## Prediciting the Test Set Results

In [52]:
y_pred_SVR = regressor_SVR.predict(X_test)
print(y_pred_SVR)

[452.9661712  449.55272829 448.25432515 ... 447.20540385 448.88816387
 453.83031595]


## Calculate R-squared (R^2) Value

In [53]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, y_pred_SVR)

print("R-squared (R^2) value for Support Vector Regression:", r2)

R-squared (R^2) value for Support Vector Regression: 0.37518682665662073
