# Artificial Neural Network

## Importing the libraries

In [20]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [21]:
tf.__version__

'2.12.0'

# Part 1 - Data Preprocessing

## Importing the dataset

In [22]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [23]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [24]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding categorical data

## Label Encoding the 'Gender" column

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le. fit_transform(x[:, 2])

In [26]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding the 'Geography" column

In [27]:
from sklearn. compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [28]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into the Training set and Test set

In [29]:
from sklearn. model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Part 2 - Building the ANN

## Initializing the ANN

In [31]:
ann = tf.keras.models.Sequential()

## Adding the ipput layer and the first hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer, dimension of y is 1 (binary), sigmoid allows the probab values if multi softmax

In [34]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

## Compiling the ANN, opti: perfom stocstic gredient decent, it updates the wight to reduce the loss between the pred and actulal. loss: the way to compute btween the pred and actual results, multi: loss = category_crossentropy

In [35]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Training the ANN on the Training set batch size: comparion is not one by one btween pred and actual epoch = learning through several iteration

In [36]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6191 - accuracy: 0.6525
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4693 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4385 - accuracy: 0.8000
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4213 - accuracy: 0.8131
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4092 - accuracy: 0.8231
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3968 - accuracy: 0.8266
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3829 - accuracy: 0.8349
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3696 - accuracy: 0.8436
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3607 - accuracy: 0.8474
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3547 - accura

# Part 4 - Making the predictions and evaluating the model

## Predicting the result of a single observation

In [37]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 128ms/step
[[False]]


## Predicting the Test set results

In [38]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print (np. concatenate ((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [39]:
from sklearn. metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print (cm)
accuracy_score (y_test, y_pred)

[[1510   85]
 [ 196  209]]


0.8595